// Generated by CoffeeScript 1.6.3
var through, _;

through = require('through');

_ = require("underscore");

module.exports = function(file) {
  var buffer;
  if (!/\.ejs/.test(file)) {
    return through();
  }
  buffer = "";
  return through(function(chunk) {
    return buffer += chunk.toString();
  }, function() {
    var compiled, e, jst, message;
    compiled = "";
    try {
      jst = _.template(buffer.toString()).source;
    } catch (_error) {
      e = _error;
      message = e.message + ' in ' + file;
      message += '\n';
      message += e.source;
      throw new Error(message);
    }
    compiled += "module.exports = " + jst + ";\n";
    this.queue(compiled);
    return this.queue(null);
  });
};
